"""SQL-like DDL serialization for Celonis ERD graphs."""

from __future__ import annotations

from collections import Counter
from typing import Any

from .erd import ERDGraph, TableNode


def graph_to_ddl(graph: ERDGraph) -> str:
    """Render a graph as a compact, SQL-like schema description.

    The output intentionally describes schema semantics rather than targeting a
    particular database dialect.  Celonis types are preserved as supplied and
    unknown types are rendered as ``UNKNOWN``.  Relationships are emitted
    after all tables so the result is easy for both humans and language models
    to scan.
    """

    if not graph.tables:
        return ""

    table_names = _table_names(graph.tables)
    table_by_id = {table.id: table for table in graph.tables}
    lines = ["-- Generated by erd-celonis"]

    _append_comment(lines, "Data pool", graph.metadata.get("data_pool_name"))
    _append_comment(lines, "Data pool ID", graph.metadata.get("data_pool_id"))
    _append_comment(lines, "Data model", graph.metadata.get("data_model_name"))
    _append_comment(lines, "Data model ID", graph.metadata.get("data_model_id"))
    lines.append("")

    for table in graph.tables:
        table_name = table_names[table.id]
        _append_comment(lines, "Table ID", table.table_id)
        if table.alias and str(table.alias) != str(table.name):
            _append_comment(lines, "Alias", table.alias)
        if getattr(table, "is_augmented", False):
            lines.append("-- Augmented table")

        if not table.columns:
            raise ValueError(
                f"Cannot render DDL for table {table.name!r}: column metadata was not loaded."
            )

        configured_primary_keys = list(table.primary_keys)
        configured_primary_keys.extend(
            str(column["name"])
            for column in table.columns
            if column.get("primary_key")
            and column.get("name") is not None
            and str(column["name"]).casefold()
            not in {key.casefold() for key in configured_primary_keys}
        )
        primary_keys = _matching_column_names(table, configured_primary_keys)
        definitions = []
        for column in table.columns:
            name = column.get("name")
            if name is None:
                continue
            type_name = _ddl_type(column.get("type"))
            definitions.append(f"  {_quote_identifier(name)} {type_name}")

        if not definitions:
            raise ValueError(
                f"Cannot render DDL for table {table.name!r}: no named columns were loaded."
            )
        if primary_keys:
            definitions.append(
                "  PRIMARY KEY ("
                + ", ".join(_quote_identifier(column) for column in primary_keys)
                + ")"
            )

        lines.append(f"CREATE TABLE {_quote_identifier(table_name)} (")
        lines.append(",\n".join(definitions))
        lines.append(");")
        lines.append("")

    for relationship in graph.relationships:
        source = table_by_id.get(relationship.source)
        target = table_by_id.get(relationship.target)
        if source is None or target is None:
            continue
        if not relationship.columns:
            _append_comment(lines, "Relationship omitted (no column mapping)", relationship.key)
            continue

        source_columns = [source_column for source_column, _ in relationship.columns]
        target_columns = [target_column for _, target_column in relationship.columns]
        _append_comment(lines, "Foreign key ID", relationship.foreign_key_id)
        lines.append(
            f"ALTER TABLE {_quote_identifier(table_names[source.id])}\n"
            "  ADD FOREIGN KEY ("
            + ", ".join(_quote_identifier(column) for column in source_columns)
            + f")\n  REFERENCES {_quote_identifier(table_names[target.id])} ("
            + ", ".join(_quote_identifier(column) for column in target_columns)
            + ");"
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _table_names(tables: list[TableNode]) -> dict[str, str]:
    """Choose readable, unique SQL names for graph tables."""

    bases = [_display_name(table) for table in tables]
    counts = Counter(name.casefold() for name in bases)
    names: dict[str, str] = {}
    used: set[str] = set()
    for table, base in zip(tables, bases, strict=True):
        if counts[base.casefold()] == 1 and base.casefold() not in used:
            name = base
        else:
            suffix = str(table.table_id or table.id).replace("/", "_")
            name = f"{base}__{suffix}"
        names[table.id] = name
        used.add(name.casefold())
    return names


def _display_name(table: TableNode) -> str:
    value = table.name or table.table_id or table.id
    return str(value)


def _matching_column_names(table: TableNode, primary_keys: list[str]) -> list[str]:
    """Return primary-key names using the spelling present in the columns."""

    actual = {str(column.get("name")).casefold(): str(column.get("name")) for column in table.columns}
    return [actual[key.casefold()] for key in primary_keys if key.casefold() in actual]


def _ddl_type(value: Any) -> str:
    if value is None or not str(value).strip():
        return "UNKNOWN"
    return " ".join(str(value).split())


def _quote_identifier(value: Any) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _append_comment(lines: list[str], label: str, value: Any) -> None:
    if value is None or str(value) == "":
        return
    safe_value = str(value).replace("\r", " ").replace("\n", " ")
    lines.append(f"-- {label}: {safe_value}")
